project_id = "qmwshhjwtqwtbjgpvbwo"

[functions.ping]
enabled = true
verify_jwt = false
import_map = "./functions/ping/deno.json"

[functions.update-navs]
enabled = true
verify_jwt = false
import_map = "./functions/update-navs/deno.json"
