version: '0.2'
ignorePaths:
  - .env
  - '**/config.toml'
  - pnpm-workspace.yaml
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - isbot
  - kysely
  - kyselify
  - nwtgck
  - piku
  - pikuh
  - pipeable
  - supabase
  - vite
  - xirr
import: []
