version: '0.2'
ignorePaths:
  - .env
  - '**/config.toml'
  - pnpm-workspace.yaml
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - nwtgck
  - piku
  - pikuh
  - supabase
import: []
