name: Health Check

on:
  schedule:
    - cron: '32 11 * * *' # Run every day at 17:02 IST (11:32 UTC)

  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Health Check
        env:
          HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL }}
        run: |
          curl -H "Accept: application/json" "$HEALTH_CHECK_URL"
